import Link from "next/link"
import styles from '../styles/Home.module.css'
import Head from "next/head"
import 'bootstrap/dist/css/bootstrap.css'

export const Layout: React.FC = ({children}) => {
  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <header className="p-3 bg-dark text-white">
      <div className="container">
        <div className="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <Link
            href="/"
          >
            <a className="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            HOME
          </a>
        </Link>
          <ul className="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li>
              <a href="/blog/articles" className="nav-link px-2 text-white">
                All articles
              </a>
            </li>
          </ul>

          <form className="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input
              type="search"
              className="form-control form-control-dark"
              placeholder="Search..."
              aria-label="Search"
            />
          </form>

          <div className="text-end">
            <button type="button" className="btn btn-outline-light me-2">
              Login
            </button>
            <button type="button" className="btn btn-warning">
              Sign-up
            </button>
          </div>
        </div>
      </div>
    </header>
      </nav>
      <article>
        {children}
      </article>

      <footer className={styles.footer}>
        <p>
          Powered by Next.js
        </p>
      </footer>


    </div>
  )
}
